global:
    resolve_timeout: 5m
    smtp_smarthost: "smtp.example.com:587"
    smtp_from: "alertmanager@example.com"
    smtp_auth_username: "alertmanager"
    smtp_auth_password: "password"
    smtp_require_tls: true

templates:
    - "/etc/alertmanager/template/*.tmpl"

route:
    group_by: ["alertname", "job", "severity"]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    receiver: "email-notifications"
    routes:
        - match:
              severity: critical
          receiver: "pager-duty-critical"
          continue: true
        - match:
              severity: warning
          receiver: "slack-notifications"
          continue: true

inhibit_rules:
    - source_match:
          severity: "critical"
      target_match:
          severity: "warning"
      equal: ["alertname", "instance"]

receivers:
    - name: "email-notifications"
      email_configs:
          - to: "team@example.com"
            send_resolved: true

    - name: "slack-notifications"
      slack_configs:
          - api_url: "https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX"
            channel: "#monitoring"
            send_resolved: true
            title: '{{ template "slack.default.title" . }}'
            text: '{{ template "slack.default.text" . }}'

    - name: "pager-duty-critical"
      pagerduty_configs:
          - service_key: "<pagerduty-service-key>"
            send_resolved: true
