groups:
    - name: todo-api-alerts
      rules:
          - alert: HighRequestLatency
            expr: http_request_duration_seconds{job="todo-api"} > 1
            for: 2m
            labels:
                severity: warning
            annotations:
                summary: "High request latency on {{ $labels.instance }}"
                description: "{{ $labels.instance }} has a request latency above 1s (current value: {{ $value }}s)"

          - alert: ApiHighErrorRate
            expr: sum(rate(http_errors_total{job="todo-api"}[5m])) / sum(rate(http_requests_total{job="todo-api"}[5m])) > 0.05
            for: 2m
            labels:
                severity: warning
            annotations:
                summary: "High error rate on API"
                description: "API error rate is above 5% (current value: {{ $value | humanizePercentage }})"

          - alert: ApiDown
            expr: up{job="todo-api"} == 0
            for: 1m
            labels:
                severity: critical
            annotations:
                summary: "API is down"
                description: "The API service is down on {{ $labels.instance }}"

          - alert: DatabaseHighErrorRate
            expr: sum(rate(database_operations_total{job="todo-api", error="true"}[5m])) / sum(rate(database_operations_total{job="todo-api"}[5m])) > 0.05
            for: 2m
            labels:
                severity: warning
            annotations:
                summary: "High database error rate"
                description: "Database error rate is above 5% (current value: {{ $value | humanizePercentage }})"

          - alert: HighDatabaseLatency
            expr: database_operation_duration_seconds{job="todo-api", quantile="0.95"} > 0.5
            for: 2m
            labels:
                severity: warning
            annotations:
                summary: "High database latency"
                description: "Database operation latency is above 500ms (current value: {{ $value }}s)"

          - alert: HighCpuUsage
            expr: (1 - avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) by (instance)) * 100 > 80
            for: 5m
            labels:
                severity: warning
            annotations:
                summary: "High CPU usage on {{ $labels.instance }}"
                description: "CPU usage is above 80% (current value: {{ $value | humanizePercentage }})"

          - alert: HighMemoryUsage
            expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 80
            for: 5m
            labels:
                severity: warning
            annotations:
                summary: "High memory usage on {{ $labels.instance }}"
                description: "Memory usage is above 80% (current value: {{ $value | humanizePercentage }})"

          - alert: HighDiskUsage
            expr: (node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) / node_filesystem_size_bytes{mountpoint="/"} * 100 > 80
            for: 5m
            labels:
                severity: warning
            annotations:
                summary: "High disk usage on {{ $labels.instance }}"
                description: "Disk usage is above 80% (current value: {{ $value | humanizePercentage }})"
