const config = {
  endOfLine: "lf",
  semi: false,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5",
  printWidth: 80,
  importOrder: [
    "^(react/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)",
    "<THIRD_PARTY_MODULES>",
    "",
    "^types$",
    "",
    "^@/env(.*)$",
    "^@/types/(.*)$",
    "^@/config/(.*)$",
    "^@/lib/(.*)$",
    "^@/hooks/(.*)$",
    "^@/api/(.*)$",
    "^@/store/(.*)$",
    "^@/features/ui/(.*)$",
    "^@/features/(.*)$",
    "^@/components/ui/(.*)$",
    "^@/components/(.*)$",
    "^@/queries/(.*)$",
    "^@/styles/(.*)$",
    "^@/assets/(.*)$",
    "^@/app/(.*)$",
    "^@/utils/(.*)$",
    "",
    "^@/constants/(.*)$",
    "",
    "^[./]",
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  plugins: ["@ianvs/prettier-plugin-sort-imports"],
}

export default config
